name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]   # main 브랜치에 push될 때 실행

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend # backend 디렉토리
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle Wrapper 실행 권한 부여 및 빌드
      # actions에서 진행하는 test에서 오류가 발생함 - 의존성을 해결하지 못함
      - name: Build backend
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --exclude-task test

      # 빌드된 JAR과 Procfile을 압축 파일로 패키징
      - name: Package backend with Procfile
        run: |
          cp Procfile build/libs/
          cd build/libs
          zip -r backend-package.zip backend-0.0.1-SNAPSHOT.jar Procfile

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: "provide-image"
          environment_name: "provide-image-env"
          region: "ap-northeast-2"
          version_label: github-${{ github.sha }}
          deployment_package: backend/build/libs/backend-package.zip